sachyfin/config/routes.rb
Rails.application.routes.draw do
  
  resources :grupos

  resources :categories
  get 'categories/:id/newrule' => 'categories#newrule', as: :newrule
  get 'categories/:id/destroyrule' => 'categories#destroyrule', as: :destroyrule

  root 'accounts#index'
  resources :transactions
  get 'transactions/:id/updatecategory' => 'transactions#updatecategory', as: :updatecategory
  get 'transactions/:id/updatefield' => 'transactions#updatefield', as: :updatefield

  resources :accounts
  post 'accounts/upload' => 'accounts#upload', as: :upload
  get 'accounts/:id/review' => 'accounts#review', as: :review
  get 'accounts/:id/showmonth' => 'accounts#showmonth', as: :showmonth
  get 'accounts/:id/resetcategory' => 'accounts#resetcategory', as: :resetcategory
  get 'accounts/:id/setbudget' => 'accounts#setbudget', as: :setbudget
  

end

sachyfin/app/models/account.rb
class Account < ActiveRecord::Base
  has_many :transactions
end

sachyfin/app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  
  include AccountsHelper
  
  before_action :set_account, only: [:show, :edit, :update, :destroy, :showmonth,:setbudget]

  before_action :all_accounts, only: [:index, :create, :update, :destroy,:upload]

  respond_to :html, :js

  # GET /accounts
  # GET /accounts.json


  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upload
    if params[:upload][:file]
      ffile = params[:upload][:file]
      name = params[:upload][:file].original_filename
      begin
        Dir.mkdir(Rails.root.join('public', 'uploads')) unless File.exists?(Rails.root.join('public', 'uploads'))
        fileOnUploadsPath = Rails.root.join('public', 'uploads', name)
        File.open(fileOnUploadsPath, 'wb') do |file|
          file.write(ffile.read)
        end
        importTransactionsFile(fileOnUploadsPath)
        #FileImportJob.perform_async(uploaded_io.original_filename)
        redirect_to accounts_path
      rescue StandardError => ex
        #Rails.logger.debug "#{GlobalConstants::DEBUG_MSG} - RallyImporterController exception: #{ex} - #{ex.message} - #{ex.backtrace.join("\n")}"
        flash[:error] = "Error: Impossible to upload file #{ex} - #{ex.message}"
        redirect_to action: 'index', status: 302
      end
    else
      flash[:error] = "Error: No upload file provided"
      redirect_to action: 'index', status: 302
    end

  end

  def review
    @account = Account.find(params[:id])
    @grupos = Grupo.all
    @categories = getCategoriesForSelect()
  end
  
  def showmonth
    @month = params['month']
  end
  
  def resetcategory
    resetCategory
    redirect_to review_path
  end
  
  def setbudget
    setBudget(params,@account.id)
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:account_number, :name, :last_import, :last_transaction)
    end
    
    def all_accounts
      @accounts = allAccounts()
    end
end

sachyfin/app/helpers/accounts_helper.rb
module AccountsHelper
  require 'spreadsheet'
  
  include CategoriesHelper
  
  def findAccount(accounts,name)
    if accounts.include?(name)
      return accounts[name][:id]
    else
      account=Account.find_by(account_number: name)
      if account.nil?
        return nil
      else
        accounts[name]={:id=>account.id,:number=>0,:lastdate=>nil}
        return account.id
      end
    end
  end
  
  # Fields : accountNumber(0)  mutationcode(1)  transactiondate(2) valuedate(3) startsaldo(4)  endsaldo(5)  amount(6)  description(7)
  # Model:
    # "account_id",      
    # "transaction_date"
    # "start_saldo",                  
    # "end_saldo",                   
    # "amount",                       
    # "description",      
    # "created_at",                                  
    # "updated_at",                                  
    # "category_id",      
    
  def importTransactionsFile(filename)
    rules = Rule.all
    accounts={}
    numberTrans=0
    book = Spreadsheet.open filename
    book.worksheets.each do |worksheet|
      skipfirst = true
      cachedId=nil
      cachedName=nil
      worksheet.each do |row|
        if skipfirst 
          skipfirst = false
          next
        end
        accountId=cachedId
        theAccountId=row[0].to_i
        if (theAccountId!=cachedName)
          puts("#########Account name #{theAccountId}")
          accountId=findAccount(accounts,theAccountId)
          if accountId.nil?
            next
          else
            cachedId=accountId
            cachedName=theAccountId
          end
        end
        puts(accounts)
        Transaction.where( account_id: accountId, transaction_date: row[2], description: row[7] ).first_or_create(  ) do |transaction|
          transaction.start_saldo = row[4]
          transaction.end_saldo = row[5]
          transaction.amount = row[6]
          transaction.category_id = setCategory(rules,row[7])
          transaction.save
        end
        accounts[cachedName][:number] +=1
        accounts[cachedName][:lastdate]=row[2]
      end
      storeAccountLastImport( accounts )
      File.delete(filename)
    end
  end
  
  def storeAccountLastImport( accounts )
    accounts.each do |key,account|
      theAccount = Account.find(account[:id])
      theAccount.last_import = DateTime.now
      theAccount.last_transaction = account[:lastdate]
      theAccount.last_amount_import = account[:number]
      theAccount.save
    end
  end
  
  def allAccounts
    accounts = Account.all
    if accounts.empty?
      createDefaults
      accounts = Account.all
    end
    return accounts
  end
  
  def createDefaults
    Account.where( name: 'Gatita', account_number: '404937587' ).first_or_create()
    Account.where( name: 'Lobito', account_number: '515840629' ).first_or_create()
    grupo = Grupo.where( name: 'Extra', budget: '300.00').first_or_create()
    Category.where( name: 'Other', budget: '100.00', grupo_id: grupo.id).first_or_create()
  end
  
  def setCategory(rules,description)
    rules.each do |rule|
      if rules.name.nil?
        next
      end
      result=description.lowercase.scan(/#{rule.name.lowercase}/)
      if !result.empty?
        return rule.category_id
      end
    end
    return 1
  end
  
  def queryTransactionsPerCategory(category_id,account_id)
    if account_id.nil?
      return Transaction.where(category_id: category_id)
    else
      return Transaction.where(category_id: category_id,account_id: account_id)
    end
  end
  
  def getGruposCategories
    return Grupo.joins(:categories).all
  end
  
  def resetCategory
    transactions = Transaction.all
    rules = Rule.all
    transactions.each do |transaction|
      transaction.category_id = setCategory(rules,transaction.description)
      transaction.save
    end
  end
  
  
  # Grouping data
  TAG_MONTH_GROUP="Group by Months"
  TAG_DATASET_GROUP="Group by Datasets"
  TAG_MONTH_GROUP_TYPE=0
  TAG_DATASET_GROUP_TYPE=1
  
  # Value Representation
  TAG_VALUE_ABSOLUTE = "Show Absolute Value"
  TAG_VALUE_PERCENTAGE = "Show Percentage Value"
  TAG_VALUE_NEGATIVE = "Show as Negative Value"
  
  TAG_VALUE_ABSOLUTE_TYPE=0
  TAG_VALUE_PERCENTAGE_TYPE=1
  TAG_VALUE_NEGATIVE_TYPE=2
  
  def getCategoryData(account)
    return getMonthlyValues(account,true,12,TAG_MONTH_GROUP_TYPE,TAG_VALUE_ABSOLUTE_TYPE,false)
  end
  
  def getGroupCategoryData(account)
    return getMonthlyValues(account,true,12,TAG_MONTH_GROUP_TYPE,TAG_VALUE_ABSOLUTE_TYPE,true)
  end
  
  def getMonthlyValues(account,sum_calculation,period,group_type,value_type,group_category)

    featureDatasets={}
    dataSet = getSampleValuesForAccount(account,period,group_category)
    dataSet.each do |key,values|
      results = nil
      # this produces something like [{"april"=>33,"may"=>22}
      if sum_calculation
        results = getSumMonthlyValues(values) 
      else
        results = getAverageMonthlyValues(values) 
      end
      featureDatasets[key]=results
    end

    case group_type 
    when TAG_MONTH_GROUP_TYPE
       return orderPerMonths(featureDatasets,value_type) 
    when TAG_DATASET_GROUP_TYPE
       return orderPerFeatures(featureDatasets,value_type)
    end
  end
  
  def orderPerMonths(datasets,value_type)  
    # To display per month and the features stacked  
    totals = {}
    if value_type == TAG_VALUE_PERCENTAGE_TYPE
      # First calculate totals
      datasets.each do |key,dataset|
        dataset.each do |result|
          result.each do |month,value|
            if !totals.include?(month)
              totals[month] = 0
            end
            totals[month]+=value
          end 
        end
      end
    end  
      
    dataFeatures ={}
    datasets.each do |key,dataset|
      dataFeatures[key]={}
      dataset.each do |result|
        result.each do |month,value|
          dataFeatures[key][month]=getValueRepresentation(value,totals[month],value_type)
        end
      end
    end  
    return formatData(dataFeatures)
  end

  def getValueRepresentation(value,total,value_type)
    newValue = value
    if !value_type.nil?
      case value_type       
      when TAG_VALUE_PERCENTAGE_TYPE
        newValue = value * 100 / total
      when TAG_VALUE_NEGATIVE_TYPE
        newValue = -1 * value
      end
    end
    return newValue
  end

  def getSampleValuesForAccount(account,period,group_category)
    data={}
     
    categories =Transaction.where(account_id:account.id).group(:category_id).pluck(:category_id)
    groupCategories={}
    categories.each do |category|
      
      results = getValuesFromDataset(category,period,
                                     Category.find(category).ctype) # this produces something like [{"april"=>33,"may"=>22}
      
      if group_category 
        theGroupId = Category.find(category).grupo_id
        
        if groupCategories.include?(theGroupId) 
          theGroupName = groupCategories[theGroupId]
        else
          theGroupName=Grupo.find(theGroupId).name
          groupCategories[theGroupId] = theGroupName
          data[theGroupName]={}
        end
               
        results.each do |key,value|         
          if !data.include?(key)
            data[theGroupName][key]=0
          end
          data[theGroupName][key] += value
        end
      else 
        data[getLabelFromId(category)]=results
      end
    end
    
    return data
  end
  
  def getSumMonthlyValues(data)
    result = Hash[ data.map { |h, v| [Date.parse(h), v] } ].group_by{ |h, v| Date::MONTHNAMES[h.month] }.map { |m,v| { m => v.sum { |vv| vv.last } } }
  end
  
  def formatData(inputData)
    data = []
    inputData.each do |key,values|
      thisDataset = { "name" => key, "data" => values }
      data.push(thisDataset)
    end
    #TODO : SHOW DATA puts(data)
    return data
  end
  
  def getValuesFromDataset(category_id,period,category_type)
    data = {}
    values = nil
    if period == 0 || period.nil?
      values = Transaction.where( category_id: category_id).order(:transaction_date).pluck(:transaction_date,:amount)
    else
      backInTime = Date.today - (period - 1).month
      queryFrom = Date.new(backInTime.year, backInTime.month,1)
      
      values = Transaction.where( 'category_id = ? AND transaction_date >= ?',category_id,queryFrom).order(:transaction_date).pluck(:transaction_date,:amount)
    end
    
    values.each do |value|
      theValue = value[1]
      data[value[0].to_s]= category_type==2? -1*theValue : theValue  #Applying category type
    end
    return data
  end
  
  def getLabelFromId(category_id)
    return Category.find(category_id).name
  end
  

  TAG_W_LINEAR_NON_STACK="Lines Non Stack"
  TAG_W_LINEAR_STACK="Lines Stack"
  TAG_W_VERTICAL_BAR='Vertical Columns'
  TAG_W_HORIZONTAL_BAR='Horizontal Bars'
  TAG_W_PIE_CHART='Pie Chart'
  TAG_W_STACKED_VERTICAL_BAR='Stacked Columns'
  TAG_W_STACKED_HORIZONTAL_BAR='Stacked Bars'  
  
  TAG_W_LINEAR_NON_STACK_TYPE=0  # RU 1
  TAG_W_LINEAR_STACK_TYPE=1      #
  TAG_W_VERTICAL_BAR_TYPE=2      
  TAG_W_HORIZONTAL_BAR_TYPE=3    # LU-0
  TAG_W_PIE_CHART_TYPE=4         # RD 2
  TAG_W_STACKED_VERTICAL_BAR_TYPE=5  #LD 3
  TAG_W_STACKED_HORIZONTAL_BAR_TYPE=6
  
  def getLast12Months
    months={}
    backInTime = Date.today - 11.months
    for i in 1..12  
      theDate = Date.new(backInTime.year, backInTime.month,1)
      months[theDate.to_s]=theDate.strftime('%b %Y')
      backInTime += 1.month
    end
    return months
  end
  
  
  def getCategoryDataPerMonth(account,month)
    dataCategory={}
    nextMonth = month.to_date + 1.month
    values = Transaction.where('account_id = ? AND transaction_date >= ? AND transaction_date < ?',account.id,month,nextMonth).group(:category_id).sum(:amount)
    categories = Category.all
    data={"actual"=>{},"budget"=>{}}
    dataGroup={"Start Saldo"=>{},"Balance"=>{},"End Saldo"=>{},"actual"=>{},"budget"=>{}}
    groupCategories={}
    saldo = 0 
    
    totalActual=0
    totalBudget=0
    

sachyfin/app/views/accounts/_account_category.html.erb
<h2>Category Budget for this account</h2>
<table class="table">
	<tr><th>Name</th><th>Default Budget</th><th>This Account Budget</th></tr>
	<%Category.all.order('name').each do |category|%>
	<tr><td><%=category.name%></td>
		<% thisBudget = category.budget.nil?? '0':category.budget%>
		<td><%= thisBudget %></td>
		<% thisAC = CategoryAccount.find_by(category_id:category.id, account_id:@account.id)%>
		<td><% thisACBudget = thisAC.nil?? thisBudget : thisAC.budget%>
		<%= form_tag( {:controller => "accounts", :action=> "setbudget",:id=> @account.id, :category_id=>category.id },{:class=>"form-inline", :method=>:get, :remote => true}) do  %>
      		<%= text_field_tag :budget, thisACBudget %>
   		<%= submit_tag "Update",class: 'btn btn-default btn-mini btn-import' %>
		<% end %>
		</td>
	</tr>
	
	<%end%>
</table>

sachyfin/app/views/accounts/_balance_grupo.html.erb
       <tr><th><%= Grupo.find(currentGrupo).name %></th>
	   	   <th><%= totalGrupo %></th>
	   	   <th><%= totalAverage%></th>
	   	   <th><%= totalBudget%></th>
	   	   <th><%= totalDeviation%></th>
	   	   </tr>	

sachyfin/app/views/accounts/_display.html.erb
<h2><%= title %></h2>

<% if data.nil? || data.size == 0 %>
     <p> No Data available for this account <%=@account.name %></p>	
<% else
     case type
        when 0 %>
        <%= line_chart data, ytitle: yLegend, height: "#{theHeight}px", stacked: false %>
    <%  when 1 %>
   	    <%= line_chart data, ytitle: yLegend, height: "#{theHeight}px", stacked: true %>
    <%  when 2 %>
        <%= column_chart data, ytitle: yLegend, height: "#{theHeight}px", stacked: false %>
    <%  when 3 %>
        <%= bar_chart data, ytitle: yLegend, height: "#{theHeight}px", stacked: false %>
    <%  when 4 %>
        <%= pie_chart data, ytitle: yLegend, height: "#{theHeight}px" %>
    <%  when 5 
          if percentage == 1 %>
            <%= column_chart data, ytitle: yLegend, height: "#{theHeight}px", stacked: true , min: 0, max: 100%>
          <% else %>
            <%= column_chart data, ytitle: yLegend, height: "#{theHeight}px", stacked: true %>
          <% end %>
    <%  when 6 %>
        <%= bar_chart data, ytitle: yLegend, height: "#{theHeight}px", stacked: true %>
    <%  end
 end %>

sachyfin/app/views/accounts/_form.html.erb
<%= simple_form_for(@account) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :account_number %>
    <%= f.input :name %>
    <%= f.input :last_import %>
    <%= f.input :last_transaction %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

sachyfin/app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

<%= render 'account_category'%>

sachyfin/app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>

<% flash.each do |key, msg| %>
    <%= content_tag :div, msg, :class => [key, " message"], :id => "notice_#{key}" %>
<% end %>

<h1>Listing Accounts</h1>

<table class="table">
  <thead>
    <tr>
      <th>Account number</th>
      <th>Last import</th>
      <th>Last transaction</th>
      <th>Last imported count</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= link_to "#{account.account_number} - #{account.name}", account %></td>
       
        <td><%= link_to account.last_import , review_path( id: account.id) %></td>
        <td><%= account.last_transaction %></td>
        <td><%= account.last_amount_import %></td>
        
        <td><%= link_to 'Edit', edit_account_path(account) %></td>
        <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', new_account_path %>

<h2>Upload transactions</h2>
<%= form_tag( {action: :upload },  multipart: true ) do %>
   <div class="form-group">
   	  <label for="name">File</label>
   	  <%= file_field_tag 'upload[file]' %>
   </div>
   <%= submit_tag "Upload",class: 'btn btn-default btn-mini' %>
<% end %>

sachyfin/app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>

sachyfin/app/views/accounts/review.html.erb
<p id="notice"><%= notice %></p>

<h1>Review last import for <%= @account.name%></h1>
<% #link_to "Reset Categories" , resetcategory_url( id: @account.id ), class: "label label-primary" , rel: "tooltip" , title: "Reset categories for all transactions" %>

<% @grupos.each do |grupo|%>
<h2><%= grupo.name%></h2>
<% categories = findCategories(grupo.id) 
   categories.each do |category|%>

     <%transactions = queryTransactionsPerCategory(category.id,@account.id)
       sum=0
       transactions.each do |transaction|
         sum+=transaction.amount
       end
       suma=sum.abs
       label="label-success"
       if suma>category.budget
       	label="label-danger"
       end%>
       <h3><%= category.name%> </h3><span class="label <%=label%>"><%=sum%></span>
       <%= render :partial => "transactions/transactions" , :locals => { :theTransactions => transactions, :theAccounts => nil , :theCategories => @categories  }%>	

  <% end%>
<% end %>

sachyfin/app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <%= "[#{@account.name} - #{@account.account_number}] History" %>
</h1>

<% data,vectorCategory=getCategoryHistoryPerAccount(@account) %>

<% if @oldMonth.nil?%>
<P> No transactions </P>
<% else%>
	
  
<p>
  <strong>Last import:</strong>
  <%= @account.last_import %>
</p>


<p>
  <strong>Last transaction:</strong>
  <%= @account.last_transaction %>
</p>


<h2>Balance [<%=@oldMonth.strftime('%b %Y')%>-<%=@lastMonth.strftime('%b %Y')%>]</h2>
<table class="table">
	<thead><th>Name</th><th>Total</th><th>Average Month</th><th>Budget</th><th>Delta</th></thead>
<% firstkey, firstvalue = vectorCategory.first
   currentGrupo=firstvalue['grupo_id']
   totalGrupo=0
   totalDeviation=0
   totalBudget=0
   totalAverage=0
   cash=0
   cashBudget=0
   vectorCategory.each do |key,catData|
     if catData['grupo_id'] != currentGrupo %>
       <%= render :partial => "balance_grupo",
                  :locals => {:currentGrupo => currentGrupo,
                  	          :totalGrupo => totalGrupo,
                  	          :totalAverage=>totalAverage,
                  	          :totalBudget=>totalBudget,
                  	          :totalDeviation=>totalDeviation}	%>
   <%   currentGrupo = catData['grupo_id']
        totalGrupo=0
        totalDeviation=0
        totalBudget=0
        totalAverage=0
      end 
      thisTotal = catData['total'] 
      thisAverage = catData['average']
      thisBudget=catData['budget'].nil?? 0 : catData['budget']
      cash += thisTotal
      if catData['ctype'] != 1
      	thisTotal *= -1
      	thisAverage *= -1
      	cashBudget -=thisBudget
      else
      	cashBudget +=thisBudget
      end
      
      totalGrupo+=thisTotal     
      totalAverage+=thisAverage
      deviation = thisAverage - thisBudget  
      if catData['ctype'] == 0
      	deviation *= -1
      end
      totalDeviation+=deviation
      totalBudget+=thisBudget
      color="green"
	  if deviation<0
	    color ="red"
	  end
      %>
   <tr style="color:<%=color%>"><td><%= catData['name'] %></td>
   	   <td><%= thisTotal %></td>
   	   <td><%= thisAverage %></td>
   	   <td><%= thisBudget%></td>
   	   <td><%= deviation%></td>
   	   </tr>
<% end %>
<%= render :partial => "balance_grupo",
                  :locals => {:currentGrupo => currentGrupo,
                  	          :totalGrupo => totalGrupo,
                  	          :totalAverage=>totalAverage,
                  	          :totalBudget=>totalBudget,
                  	          :totalDeviation=>totalDeviation}%>
 <% cashAverage = cash*1.0/@numberMonths%>
 <thead><th>Posible cash</th>
	   	   <th><%= cash %></th>
	   	   <th><%= cashAverage %></th>
	   	   <th><%= cashBudget%></th>
	   	   <th><%= cashAverage-cashBudget %></th>
	   	   </thead>
</table>
<%= render :partial => "display", :locals => { :title => "Saldo Evolution", 
	                                           :data => getSaldoEvolution12Months(@account),
	                                           :type => 0,
	                                           :percentage => 0,
	                                           :yLegend => "Euros",
	                                           :theHeight => 200}%>
<strong>Click month to view month history</strong>
<table class="table">
	<tr>
	<% getLast12Months.each do |key,month| %>
	<td><%= link_to month, showmonth_url(id: @account.id, month: key)%></td>
	<% end%>
</table>
	                                           
<%= render :partial => "display", :locals => { :title => "Groups", 
	                                           :data => getGroupCategoryData(@account),
	                                           :type => 5,
	                                           :percentage => 0,
	                                           :yLegend => "Euros",
	                                           :theHeight => 350}%>

<%= render :partial => "display", :locals => { :title => "Category", 
	                                           :data => getCategoryData(@account),
	                                           :type => 5,
	                                           :percentage => 0,
	                                           :yLegend => "Euros",
	                                           :theHeight => 350}%>


<h2>History from [<%=@oldMonth.strftime('%b %Y')%>-<%=@lastMonth.strftime('%b %Y')%>]</h2>

   <%data.each do |categoryName,values| %>
   <h3><%=categoryName%></h3>
   <% if values.empty?%>
     <p>No values for this category </p>
   <%else%>
   <%= column_chart values, ytitle: "Euros", height: "200px", stacked: false %>
   <% end %>
<% end %>	
<% end %>
<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>

sachyfin/app/views/accounts/showmonth.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <%= "[#{@account.name} - #{@account.account_number}] [#{@month}] Movements" %>
</h1>
<%= link_to 'Back',  @account %>
<% dataCategoryToDisplay, dataGroup, dataCategory = getCategoryDataPerMonth(@account,@month)%>
<table class="table">
	<thead><th>Category</th><th>Actual</th><th>Budget</th>
		   <th>Deviation</th><th>Percentage</th>
	</thead>
<% dataCategory.each do |key,categoryData|
    color="green"
    if categoryData["deviation"]<0
      color ="red"
    end%>
	
	<tr style="color:<%=color%>">
		<td><%=key%></td>
		<td><%=categoryData["actual"]%></td>
		<td><%=categoryData["budget"]%></td>
		<td ><%=categoryData["deviation"]%></td>
		<td><%=categoryData["percentage"]%>%</td>
	</tr>
<% end %>
</table>
<%= render :partial => "display", :locals => { :title => "Category Groups", 
	                                           :data => dataGroup,
	                                           :type => 2,
	                                           :percentage => 0,
	                                           :yLegend => "Euros",
	                                           :theHeight => 350}%>
<%= render :partial => "display", :locals => { :title => "Categories", 
	                                           :data => dataCategoryToDisplay,
	                                           :type => 2,
	                                           :percentage => 0,
	                                           :yLegend => "Euros",
	                                           :theHeight => 350}%>


<h2>Transactions</h2>
<% transactions = getTransactionsForMonth(@account,@month) %>

<%= render :partial => "transactions/transactions" , :locals => { :theTransactions => transactions, :theAccounts => nil , :theCategories => getCategoriesForSelect }%>	