sachyfin/config/routes.rb
Rails.application.routes.draw do
  
  resources :grupos

  resources :categories
  get 'categories/:id/newrule' => 'categories#newrule', as: :newrule
  get 'categories/:id/destroyrule' => 'categories#destroyrule', as: :destroyrule

  root 'accounts#index'
  resources :transactions
  get 'transactions/:id/updatecategory' => 'transactions#updatecategory', as: :updatecategory
  get 'transactions/:id/updatefield' => 'transactions#updatefield', as: :updatefield

  resources :accounts
  post 'accounts/upload' => 'accounts#upload', as: :upload
  get 'accounts/:id/review' => 'accounts#review', as: :review
  get 'accounts/:id/showmonth' => 'accounts#showmonth', as: :showmonth
  get 'accounts/:id/resetcategory' => 'accounts#resetcategory', as: :resetcategory
  get 'accounts/:id/setbudget' => 'accounts#setbudget', as: :setbudget
  

end

sachyfin/app/models/grupo.rb
class Grupo < ActiveRecord::Base
  has_many :categories
end

sachyfin/app/controllers/grupos_controller.rb
class GruposController < ApplicationController
  before_action :set_grupo, only: [:show, :edit, :update, :destroy]

  # GET /grupos
  # GET /grupos.json
  def index
    @grupos = Grupo.all
  end

  # GET /grupos/1
  # GET /grupos/1.json
  def show
  end

  # GET /grupos/new
  def new
    @grupo = Grupo.new
  end

  # GET /grupos/1/edit
  def edit
  end

  # POST /grupos
  # POST /grupos.json
  def create
    @grupo = Grupo.new(grupo_params)

    respond_to do |format|
      if @grupo.save
        format.html { redirect_to @grupo, notice: 'Grupo was successfully created.' }
        format.json { render :show, status: :created, location: @grupo }
      else
        format.html { render :new }
        format.json { render json: @grupo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grupos/1
  # PATCH/PUT /grupos/1.json
  def update
    respond_to do |format|
      if @grupo.update(grupo_params)
        format.html { redirect_to @grupo, notice: 'Grupo was successfully updated.' }
        format.json { render :show, status: :ok, location: @grupo }
      else
        format.html { render :edit }
        format.json { render json: @grupo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grupos/1
  # DELETE /grupos/1.json
  def destroy
    @grupo.destroy
    respond_to do |format|
      format.html { redirect_to grupos_url, notice: 'Grupo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grupo
      @grupo = Grupo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def grupo_params
      params.require(:grupo).permit(:name,:budget)
    end
end

sachyfin/app/helpers/grupos_helper.rb
module GruposHelper
end

sachyfin/app/views/grupos/_form.html.erb
<%= simple_form_for(@grupo) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :budget %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

sachyfin/app/views/grupos/edit.html.erb
<h1>Editing Grupo</h1>

<%= render 'form' %>

<%= link_to 'Show', @grupo %> |
<%= link_to 'Back', grupos_path %>

sachyfin/app/views/grupos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Grupos</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Budget</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @grupos.each do |grupo| %>
      <tr>
        <td><%= grupo.name %></td>
        <td><%= grupo.budget %></td>
        <td><%= link_to 'Show', grupo %></td>
        <td><%= link_to 'Edit', edit_grupo_path(grupo) %></td>
        <td><%= link_to 'Destroy', grupo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Grupo', new_grupo_path %>

sachyfin/app/views/grupos/new.html.erb
<h1>New Grupo</h1>

<%= render 'form' %>

<%= link_to 'Back', grupos_path %>

sachyfin/app/views/grupos/show.html.erb
<p id="notice"><%= notice %></p>

<h2>Grupo</h2>
  <dl class="dl-horizontal"> 

  <dt><strong>Name:</strong></dt>
  <dd><%= @grupo.name %></dd>
  <dt><strong>Budget:</strong>
  <dd><%= @grupo.budget %></dd>

</dl>


<%= link_to 'Edit', edit_grupo_path(@grupo) %> |
<%= link_to 'Back', grupos_path %>