sachyfin/config/routes.rb
Rails.application.routes.draw do
  
  resources :grupos

  resources :categories
  get 'categories/:id/newrule' => 'categories#newrule', as: :newrule
  get 'categories/:id/destroyrule' => 'categories#destroyrule', as: :destroyrule

  root 'accounts#index'
  resources :transactions
  get 'transactions/:id/updatecategory' => 'transactions#updatecategory', as: :updatecategory
  get 'transactions/:id/updatefield' => 'transactions#updatefield', as: :updatefield

  resources :accounts
  post 'accounts/upload' => 'accounts#upload', as: :upload
  get 'accounts/:id/review' => 'accounts#review', as: :review
  get 'accounts/:id/showmonth' => 'accounts#showmonth', as: :showmonth
  get 'accounts/:id/resetcategory' => 'accounts#resetcategory', as: :resetcategory
  get 'accounts/:id/setbudget' => 'accounts#setbudget', as: :setbudget
  

end

sachyfin/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sachyfin</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


  <div class="row">
    <div class="col-md-1">
      <h3 align="center">Finanzas</h3>
      <ul class="nav nav-pills nav-stacked">    
      <li class="nav-item"><%= link_to "Accounts" , accounts_path, class: "nav-link" %></li>  	
      <li class="nav-item"><%= link_to "Groups" , grupos_path, class: "nav-link" %></li>
      <li class="nav-item"><%= link_to "Categorias" , categories_path, class: "nav-link" %></li>
      </ul>	
    </div>
    <div class="col-md-10">
      <%= yield %>
    </div>
  </div>

</body>
</html>